# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banks.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'banks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\"5\n\x0e\x44\x65positRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"!\n\x0f\x44\x65positResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"6\n\x0fWithdrawRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\"\"\n\x10WithdrawResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\"#\n\x0cQueryRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\" \n\rQueryResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\x32\x94\x01\n\x0b\x42\x61nkService\x12,\n\x07\x44\x65posit\x12\x0f.DepositRequest\x1a\x10.DepositResponse\x12/\n\x08Withdraw\x12\x10.WithdrawRequest\x1a\x11.WithdrawResponse\x12&\n\x05Query\x12\r.QueryRequest\x1a\x0e.QueryResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPOSITREQUEST']._serialized_start=15
  _globals['_DEPOSITREQUEST']._serialized_end=68
  _globals['_DEPOSITRESPONSE']._serialized_start=70
  _globals['_DEPOSITRESPONSE']._serialized_end=103
  _globals['_WITHDRAWREQUEST']._serialized_start=105
  _globals['_WITHDRAWREQUEST']._serialized_end=159
  _globals['_WITHDRAWRESPONSE']._serialized_start=161
  _globals['_WITHDRAWRESPONSE']._serialized_end=195
  _globals['_QUERYREQUEST']._serialized_start=197
  _globals['_QUERYREQUEST']._serialized_end=232
  _globals['_QUERYRESPONSE']._serialized_start=234
  _globals['_QUERYRESPONSE']._serialized_end=266
  _globals['_BANKSERVICE']._serialized_start=269
  _globals['_BANKSERVICE']._serialized_end=417
# @@protoc_insertion_point(module_scope)
