# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: banks.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'banks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x0b\x62\x61nks.proto\x12\x04\x62\x61nk\"L\n\x0e\x44\x65positRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x15\n\rlogical_clock\x18\x03 \x01(\x05\"M\n\x0fWithdrawRequest\x12\x13\n\x0b\x63ustomer_id\x18\x01 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x02 \x01(\x05\x12\x15\n\rlogical_clock\x18\x03 \x01(\x05\"y\n\x10PropagateRequest\x12\x11\n\tbranch_id\x18\x01 \x01(\x05\x12\x1b\n\x13\x63ustomer_request_id\x18\x02 \x01(\x05\x12\x0e\n\x06\x61mount\x18\x03 \x01(\x05\x12\x0e\n\x06\x61\x63tion\x18\x04 \x01(\t\x12\x15\n\rlogical_clock\x18\x05 \x01(\x05\"2\n\x08Response\x12\x0f\n\x07success\x18\x01 \x01(\x08\x12\x15\n\rlogical_clock\x18\x02 \x01(\x05\x32\xa8\x01\n\rBranchService\x12/\n\x07\x44\x65posit\x12\x14.bank.DepositRequest\x1a\x0e.bank.Response\x12\x31\n\x08Withdraw\x12\x15.bank.WithdrawRequest\x1a\x0e.bank.Response\x12\x33\n\tPropagate\x12\x16.bank.PropagateRequest\x1a\x0e.bank.Responseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_DEPOSITREQUEST']._serialized_start=21
  _globals['_DEPOSITREQUEST']._serialized_end=97
  _globals['_WITHDRAWREQUEST']._serialized_start=99
  _globals['_WITHDRAWREQUEST']._serialized_end=176
  _globals['_PROPAGATEREQUEST']._serialized_start=178
  _globals['_PROPAGATEREQUEST']._serialized_end=299
  _globals['_RESPONSE']._serialized_start=301
  _globals['_RESPONSE']._serialized_end=351
  _globals['_BRANCHSERVICE']._serialized_start=354
  _globals['_BRANCHSERVICE']._serialized_end=522
# @@protoc_insertion_point(module_scope)
