# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# NO CHECKED-IN PROTOBUF GENCODE
# source: protos/banks.proto
# Protobuf Python Version: 5.27.2
"""Generated protocol buffer code."""
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import runtime_version as _runtime_version
from google.protobuf import symbol_database as _symbol_database
from google.protobuf.internal import builder as _builder
_runtime_version.ValidateProtobufRuntimeVersion(
    _runtime_version.Domain.PUBLIC,
    5,
    27,
    2,
    '',
    'protos/banks.proto'
)
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\x12protos/banks.proto\x12\x07\x62\x61nking\"\x1a\n\x0cQueryRequest\x12\n\n\x02id\x18\x01 \x01(\x05\" \n\rQueryResponse\x12\x0f\n\x07\x62\x61lance\x18\x01 \x01(\x05\"+\n\x0e\x44\x65positRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05money\x18\x02 \x01(\x05\"%\n\x13TransactionResponse\x12\x0e\n\x06result\x18\x01 \x01(\t\",\n\x0fWithdrawRequest\x12\n\n\x02id\x18\x01 \x01(\x05\x12\r\n\x05money\x18\x02 \x01(\x05\x32\xe8\x02\n\x0e\x42\x61nkingService\x12\x36\n\x05Query\x12\x15.banking.QueryRequest\x1a\x16.banking.QueryResponse\x12@\n\x07\x44\x65posit\x12\x17.banking.DepositRequest\x1a\x1c.banking.TransactionResponse\x12\x42\n\x08Withdraw\x12\x18.banking.WithdrawRequest\x1a\x1c.banking.TransactionResponse\x12J\n\x11Propogate_Deposit\x12\x17.banking.DepositRequest\x1a\x1c.banking.TransactionResponse\x12L\n\x12Propogate_Withdraw\x12\x18.banking.WithdrawRequest\x1a\x1c.banking.TransactionResponseb\x06proto3')

_globals = globals()
_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, _globals)
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'protos.banks_pb2', _globals)
if not _descriptor._USE_C_DESCRIPTORS:
  DESCRIPTOR._loaded_options = None
  _globals['_QUERYREQUEST']._serialized_start=31
  _globals['_QUERYREQUEST']._serialized_end=57
  _globals['_QUERYRESPONSE']._serialized_start=59
  _globals['_QUERYRESPONSE']._serialized_end=91
  _globals['_DEPOSITREQUEST']._serialized_start=93
  _globals['_DEPOSITREQUEST']._serialized_end=136
  _globals['_TRANSACTIONRESPONSE']._serialized_start=138
  _globals['_TRANSACTIONRESPONSE']._serialized_end=175
  _globals['_WITHDRAWREQUEST']._serialized_start=177
  _globals['_WITHDRAWREQUEST']._serialized_end=221
  _globals['_BANKINGSERVICE']._serialized_start=224
  _globals['_BANKINGSERVICE']._serialized_end=584
# @@protoc_insertion_point(module_scope)
