# Generated by the gRPC Python protocol compiler plugin. DO NOT EDIT!
"""Client and server classes corresponding to protobuf-defined services."""
import grpc
import warnings

from protos import banks_pb2 as protos_dot_banks__pb2

GRPC_GENERATED_VERSION = '1.67.0'
GRPC_VERSION = grpc.__version__
_version_not_supported = False

try:
    from grpc._utilities import first_version_is_lower
    _version_not_supported = first_version_is_lower(GRPC_VERSION, GRPC_GENERATED_VERSION)
except ImportError:
    _version_not_supported = True

if _version_not_supported:
    raise RuntimeError(
        f'The grpc package installed is at version {GRPC_VERSION},'
        + f' but the generated code in protos/banks_pb2_grpc.py depends on'
        + f' grpcio>={GRPC_GENERATED_VERSION}.'
        + f' Please upgrade your grpc module to grpcio>={GRPC_GENERATED_VERSION}'
        + f' or downgrade your generated code using grpcio-tools<={GRPC_VERSION}.'
    )


class BankingServiceStub(object):
    """The service definition
    """

    def __init__(self, channel):
        """Constructor.

        Args:
            channel: A grpc.Channel.
        """
        self.Query = channel.unary_unary(
                '/banking.BankingService/Query',
                request_serializer=protos_dot_banks__pb2.QueryRequest.SerializeToString,
                response_deserializer=protos_dot_banks__pb2.QueryResponse.FromString,
                _registered_method=True)
        self.Deposit = channel.unary_unary(
                '/banking.BankingService/Deposit',
                request_serializer=protos_dot_banks__pb2.DepositRequest.SerializeToString,
                response_deserializer=protos_dot_banks__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Withdraw = channel.unary_unary(
                '/banking.BankingService/Withdraw',
                request_serializer=protos_dot_banks__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=protos_dot_banks__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Propogate_Deposit = channel.unary_unary(
                '/banking.BankingService/Propogate_Deposit',
                request_serializer=protos_dot_banks__pb2.DepositRequest.SerializeToString,
                response_deserializer=protos_dot_banks__pb2.TransactionResponse.FromString,
                _registered_method=True)
        self.Propogate_Withdraw = channel.unary_unary(
                '/banking.BankingService/Propogate_Withdraw',
                request_serializer=protos_dot_banks__pb2.WithdrawRequest.SerializeToString,
                response_deserializer=protos_dot_banks__pb2.TransactionResponse.FromString,
                _registered_method=True)


class BankingServiceServicer(object):
    """The service definition
    """

    def Query(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propogate_Deposit(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')

    def Propogate_Withdraw(self, request, context):
        """Missing associated documentation comment in .proto file."""
        context.set_code(grpc.StatusCode.UNIMPLEMENTED)
        context.set_details('Method not implemented!')
        raise NotImplementedError('Method not implemented!')


def add_BankingServiceServicer_to_server(servicer, server):
    rpc_method_handlers = {
            'Query': grpc.unary_unary_rpc_method_handler(
                    servicer.Query,
                    request_deserializer=protos_dot_banks__pb2.QueryRequest.FromString,
                    response_serializer=protos_dot_banks__pb2.QueryResponse.SerializeToString,
            ),
            'Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Deposit,
                    request_deserializer=protos_dot_banks__pb2.DepositRequest.FromString,
                    response_serializer=protos_dot_banks__pb2.TransactionResponse.SerializeToString,
            ),
            'Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Withdraw,
                    request_deserializer=protos_dot_banks__pb2.WithdrawRequest.FromString,
                    response_serializer=protos_dot_banks__pb2.TransactionResponse.SerializeToString,
            ),
            'Propogate_Deposit': grpc.unary_unary_rpc_method_handler(
                    servicer.Propogate_Deposit,
                    request_deserializer=protos_dot_banks__pb2.DepositRequest.FromString,
                    response_serializer=protos_dot_banks__pb2.TransactionResponse.SerializeToString,
            ),
            'Propogate_Withdraw': grpc.unary_unary_rpc_method_handler(
                    servicer.Propogate_Withdraw,
                    request_deserializer=protos_dot_banks__pb2.WithdrawRequest.FromString,
                    response_serializer=protos_dot_banks__pb2.TransactionResponse.SerializeToString,
            ),
    }
    generic_handler = grpc.method_handlers_generic_handler(
            'banking.BankingService', rpc_method_handlers)
    server.add_generic_rpc_handlers((generic_handler,))
    server.add_registered_method_handlers('banking.BankingService', rpc_method_handlers)


 # This class is part of an EXPERIMENTAL API.
class BankingService(object):
    """The service definition
    """

    @staticmethod
    def Query(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/Query',
            protos_dot_banks__pb2.QueryRequest.SerializeToString,
            protos_dot_banks__pb2.QueryResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/Deposit',
            protos_dot_banks__pb2.DepositRequest.SerializeToString,
            protos_dot_banks__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/Withdraw',
            protos_dot_banks__pb2.WithdrawRequest.SerializeToString,
            protos_dot_banks__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propogate_Deposit(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/Propogate_Deposit',
            protos_dot_banks__pb2.DepositRequest.SerializeToString,
            protos_dot_banks__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)

    @staticmethod
    def Propogate_Withdraw(request,
            target,
            options=(),
            channel_credentials=None,
            call_credentials=None,
            insecure=False,
            compression=None,
            wait_for_ready=None,
            timeout=None,
            metadata=None):
        return grpc.experimental.unary_unary(
            request,
            target,
            '/banking.BankingService/Propogate_Withdraw',
            protos_dot_banks__pb2.WithdrawRequest.SerializeToString,
            protos_dot_banks__pb2.TransactionResponse.FromString,
            options,
            channel_credentials,
            insecure,
            call_credentials,
            compression,
            wait_for_ready,
            timeout,
            metadata,
            _registered_method=True)
